# docker-compose build
version: '3.9'

#uncomment all volumes-related stuff if you want to keep cache persistent
#volumes:
#  postgis-data: postgis-data:/var/lib/postgresql/data

services:

  db:
    image: kartoza/postgis:15
    volumes:
      - ./postgis-data:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=cache
      - POSTGRES_USER=cache
      - POSTGRES_PASS=cache1234
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - RUN_AS_ROOT=true
    ports:
      - "127.0.0.1:5440:5432"
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=docker pg_isready -h 127.0.0.1 -U docker -d gis"
